### ISSUE TITLE
Mehrere Fehler: Siehe https://github.com/hschottm/tags/issues

### ISSUE THREAD

**Issue by jankout** [1up-lab/contao-tags#2]
Hallo, 

die Erweiterung, die Sie übernommen haben, verursacht einiges Fehlverhalten. Können Sie sich das bitte anschauen und ggf. korrigieren? Das wäre toll. 

[https://github.com/hschottm/tags/issues](https://github.com/hschottm/tags/issues)

Schon jetzt danke ich Ihnen für Ihre Antwort und wünsche Ihnen noch einen schönen Tag.

Mit freundlichen Grüßen,

Jan

**Comment by bytehead** [comment]
Diese Erweiterung wird von uns nicht supportet. Es ist nur ein Mirror für ein altes (sehr altes) Projekt.

**Comment by sheeep** [comment]
https://github.com/1up-lab/contao-tags/commit/42de64d5efd529f5dbf2ec72cdfb029c22c891ea

**Comment by bytehead** [comment]
Fehler besser im Originalrepository (https://github.com/hschottm/tags/issues) melden :)
