### ISSUE TITLE
Error after update to 4.9.0 -tl_settings

### ISSUE THREAD

**Issue by planepix** [1up-lab/contao-tags#3]
Hi guys,

i reported an error in another bundle repo guess i thought the error occured from this bundle.
Finally it come from the bundle coontao-tags.
Using of ”tl_settings” is obsolute up from Contao 4.9.
Link to reported issue: https://github.com/OMOSde/contao-om-backend/issues/49#issuecomment-588161177

Thomas

**Comment by bytehead** [comment]
This repository is just a mirror is not supported in any way. Please use https://github.com/hschottm/tags.
